### ISSUE TITLE
Ability to upload 360° photos

### ISSUE THREAD

**Issue by sirkitree** [LullabotVR/360gallerysite#1]
Create a content type where a user can upload a 360° photo.

**Comment by mrdavidburns** [comment]
@sirkitree I have html5_upload locally but apparently it needs to be multiple value upload field? Why can't we have drag and drop for individual file?

Might port this to backdrop to give us that functionality. https://www.drupal.org/project/dragndrop_upload

**Comment by sirkitree** [comment]
Multiple will most likely be desired, but at that point we may want to use something like filebrowser instead of nodes to manage files. For now I think it's fine to have just one pic per node for MVP. Drag and drop is also a nice to have IMHO.

**Comment by sirkitree** [comment]
The basic content type has been created and is on dev.
